#!/bin/sh

build () {
    ./configure > Makefile
    make -j8
}

clean () {
    ./configure > Makefile
    make clean
}

format () {
    # TODO: Check if any files exist before attempting to format them.
    #clang-format -i $(find . -type f -name '*.c')
    clang-format -i $(find . -type f -name '*.cpp')
    clang-format -i $(find . -type f -name '*.h')
}

lint () {
    clang-tidy --checks='bugprone*,modernize*,cppcoreguidelines*' --use-color $(find . -type f -wholename '*.cpp') -- -I. | less -r
}

run () {
    ./mach
    make tar-drive.tar

    qemu-system-x86_64 \
        -serial mon:stdio \
        -kernel leonardo.bin \
        -hda tar-drive.tar \
        -d guest_errors \
        -audiodev pa,id=snd0 -machine pcspk-audiodev=snd0 \
        -machine pcspk-audiodev=snd0 \
        -vga std \
        -d cpu_reset \
        -m 64
}

runcurses () {
    ./mach
    make tar-drive.tar

    qemu-system-x86_64 \
        -curses \
        -serial file:serial.log \
        -kernel leonardo.bin \
        -hda tar-drive.tar \
        -m 64
}

iso () {
    mkdir -p build/iso/boot/grub
    cp leonardo.bin build/iso/boot/leonardo.bin
    echo "menuentry \"leonardo\" { multiboot /boot/leonardo.bin }" > build/iso/boot/grub/grub.cfg
    grub-mkrescue -o build/iso/leonardo.iso build/iso
}

action=$*
if [ -z "${action}" ]
then
  action="build"
fi


for command in ${action}
do
    "${command}"
done
